import { useState } from "react";
import { superAdminApi } from "../../api/superAdminApi";
const initialForm = { businessName: "", ownerName: "", ownerEmail: "", ownerPhone: "", branchName: "Principal", branchAddress: "", branchPhone: "", plan: "STARTER", billingCycle: "MONTHLY", trialDays: 7, currency: "USD" };
export default function SuperAdminCreateBarbershop() {
  const [form, setForm] = useState(initialForm); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [created, setCreated] = useState(null);
  function update(name, value) { setForm((prev) => ({ ...prev, [name]: value })); }
  async function submit(e) { e.preventDefault(); setError(""); setCreated(null); if (!form.businessName.trim()) return setError("Ingresa el nombre de la barbería."); if (!form.ownerName.trim()) return setError("Ingresa el nombre del dueño."); if (!form.ownerEmail.includes("@")) return setError("Ingresa un correo válido."); if (!form.branchName.trim()) return setError("Ingresa la sede principal."); try { setSaving(true); const payload = { ...form, businessName: form.businessName.trim(), ownerName: form.ownerName.trim(), ownerEmail: form.ownerEmail.trim().toLowerCase(), ownerPhone: form.ownerPhone.trim(), branchName: form.branchName.trim(), branchAddress: form.branchAddress.trim(), branchPhone: form.branchPhone.trim(), trialDays: Number(form.trialDays || 0) }; const response = await superAdminApi.createTenant(payload); setCreated(response || {}); setForm(initialForm); } catch (e) { setError(e.message || "No se pudo crear la barbería."); } finally { setSaving(false); } }
  return <div className="mx-auto max-w-5xl space-y-6"><section className="rounded-[2rem] border border-[#E9DED0] bg-gradient-to-br from-[#FFFCF8] to-[#F4E8D7] p-6"><h1 className="text-3xl font-black">Crear barbería</h1><p className="mt-2 text-sm font-semibold text-[#7A6F63]">Registra el negocio, crea su sede principal y asigna el plan inicial desde el panel web.</p></section>{error && <div className="rounded-2xl border border-red-100 bg-red-50 p-4 font-bold text-red-700">{error}</div>}{created && <div className="rounded-3xl border border-emerald-100 bg-emerald-50 p-5"><h2 className="text-xl font-black text-emerald-800">Barbería creada con éxito</h2><div className="mt-3 grid gap-2 text-sm font-bold text-emerald-900 sm:grid-cols-2"><p>Negocio: {created.businessName || "-"}</p><p>Código: {created.code || "-"}</p><p>Usuario: {created.ownerEmail || created.email || "-"}</p><p>Contraseña temporal: 123456</p></div></div>}
    <form onSubmit={submit} className="space-y-5"><Card title="Datos del negocio"><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre de la barbería" value={form.businessName} onChange={(v) => update("businessName", v)} /><Field label="Nombre sede principal" value={form.branchName} onChange={(v) => update("branchName", v)} /><Field label="Dirección sede" value={form.branchAddress} onChange={(v) => update("branchAddress", v)} /><Field label="Teléfono sede" value={form.branchPhone} onChange={(v) => update("branchPhone", v)} /></div></Card><Card title="Datos del dueño"><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre del dueño" value={form.ownerName} onChange={(v) => update("ownerName", v)} /><Field label="Correo del dueño" type="email" value={form.ownerEmail} onChange={(v) => update("ownerEmail", v)} /><Field label="Teléfono del dueño" value={form.ownerPhone} onChange={(v) => update("ownerPhone", v)} /></div></Card><Card title="Plan inicial"><div className="grid gap-4 md:grid-cols-4"><Select label="Plan" value={form.plan} onChange={(v) => update("plan", v)} options={["STARTER", "PRO", "GODS_AI"]} /><Select label="Ciclo" value={form.billingCycle} onChange={(v) => update("billingCycle", v)} options={["MONTHLY", "SEMIANNUAL", "YEARLY"]} /><Select label="Moneda" value={form.currency} onChange={(v) => update("currency", v)} options={["USD", "PEN"]} /><Field label="Días de prueba" type="number" value={form.trialDays} onChange={(v) => update("trialDays", v)} /></div></Card><button disabled={saving} className="w-full rounded-2xl bg-[#AF8750] px-5 py-4 text-base font-black text-white shadow-lg disabled:opacity-60">{saving ? "Creando..." : "Crear barbería"}</button></form></div>;
}
function Card({ title, children }) { return <section className="rounded-3xl border border-[#E9DED0] bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-black">{title}</h2>{children}</section>; }
function Field({ label, value, onChange, type = "text" }) { return <label className="block"><span className="mb-2 block text-sm font-black text-[#7A6F63]">{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="w-full rounded-2xl border border-[#E9DED0] bg-white px-4 py-3 font-bold outline-none focus:border-[#AF8750]" /></label>; }
function Select({ label, value, onChange, options }) { return <label className="block"><span className="mb-2 block text-sm font-black text-[#7A6F63]">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="w-full rounded-2xl border border-[#E9DED0] bg-white px-4 py-3 font-bold outline-none focus:border-[#AF8750]">{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
