import { useEffect, useMemo, useState } from "react";
import { superAdminApi } from "../../api/superAdminApi";
function statusLabel(status) { switch ((status || "").toUpperCase()) { case "ACTIVE": return "Activa"; case "TRIAL": return "Trial"; case "PENDING_REVIEW": return "Pendiente"; case "SUSPENDED": return "Suspendida"; case "EXPIRED": return "Vencida"; default: return status || "-"; } }
function planLabel(plan) { switch ((plan || "").toUpperCase()) { case "STARTER": return "Starter"; case "PRO": return "Pro"; case "GODS_AI": return "Gods AI"; default: return plan || "-"; } }
export default function SuperAdminTenants() {
  const [items, setItems] = useState([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { try { setLoading(true); setError(""); setItems(await superAdminApi.getTenants()); } catch (e) { setError(e.message || "No se pudo cargar la lista."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return items; return items.filter((item) => [item.businessName, item.plan, item.status, item.tenantId, item.code].join(" ").toLowerCase().includes(q)); }, [items, query]);
  return <div className="space-y-6"><section className="rounded-[2rem] border border-[#E9DED0] bg-gradient-to-br from-[#FFFCF8] to-[#F4E8D7] p-6"><h1 className="text-3xl font-black">Barberías</h1><p className="mt-2 text-sm font-semibold text-[#7A6F63]">Consulta y supervisa cada negocio registrado.</p><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nombre, plan, estado, código o ID" className="mt-5 w-full rounded-2xl border border-[#E9DED0] bg-white px-4 py-3 font-bold outline-none focus:border-[#AF8750]" /></section>{loading && <div className="rounded-3xl bg-white p-8 font-bold">Cargando barberías...</div>}{error && <div className="rounded-3xl border border-red-100 bg-red-50 p-5 font-bold text-red-700">{error}</div>}{!loading && !error && filtered.length === 0 && <div className="rounded-3xl border border-[#E9DED0] bg-white p-10 text-center"><h2 className="text-xl font-black">No hay barberías para mostrar</h2><p className="mt-2 text-sm font-semibold text-[#7A6F63]">Cuando registres nuevos negocios o si tu búsqueda coincide, aparecerán aquí.</p></div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article key={item.tenantId || item.code || JSON.stringify(item)} className="rounded-3xl border border-[#E9DED0] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-black leading-tight">{item.businessName || "-"}</h2><span className="rounded-full bg-[#FFFCF8] px-3 py-1 text-xs font-black text-[#7A6F63]">ID {item.tenantId || "-"}</span></div><div className="mt-4 flex flex-wrap gap-2"><Chip tone="blue">{planLabel(item.plan)}</Chip><Chip tone="gold">{statusLabel(item.status)}</Chip>{item.code && <Chip tone="gray">{item.code}</Chip>}</div><div className="mt-5 space-y-1 text-sm font-bold text-[#7A6F63]"><p>Dueño: {item.ownerName || "-"}</p><p>Email: {item.ownerEmail || "-"}</p><p>Teléfono: {item.ownerPhone || "-"}</p></div></article>)}</div></div>;
}
function Chip({ children, tone = "gold" }) { const tones = { gold: "bg-[#F4E8D7] text-[#AF8750]", blue: "bg-blue-50 text-blue-700", gray: "bg-gray-100 text-gray-700" }; return <span className={`rounded-full px-3 py-1 text-xs font-black ${tones[tone]}`}>{children}</span>; }
