import { useEffect, useState } from "react";
import { superAdminApi } from "../../api/superAdminApi";
export default function SuperAdminPayments() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [processingId, setProcessingId] = useState(null); const [error, setError] = useState("");
  async function load() { try { setLoading(true); setError(""); setItems(await superAdminApi.getPendingPayments()); } catch (e) { setError(e.message || "No se pudieron cargar los pagos."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function approve(paymentId) { if (!window.confirm("¿Deseas aprobar este pago pendiente?")) return; try { setProcessingId(paymentId); await superAdminApi.approvePayment(paymentId); await load(); } catch (e) { alert(e.message || "No se pudo aprobar el pago."); } finally { setProcessingId(null); } }
  async function reject(paymentId) { if (!window.confirm("¿Deseas rechazar este pago pendiente?")) return; try { setProcessingId(paymentId); await superAdminApi.rejectPayment(paymentId); await load(); } catch (e) { alert(e.message || "No se pudo rechazar el pago."); } finally { setProcessingId(null); } }
  return <div className="space-y-6"><section className="rounded-[2rem] border border-[#E9DED0] bg-white p-6"><h1 className="text-3xl font-black">Pagos pendientes</h1><p className="mt-2 text-sm font-semibold text-[#7A6F63]">Valida operaciones enviadas por barberías y activa la cuenta cuando corresponda.</p></section>{loading && <div className="rounded-3xl bg-white p-8 font-bold">Cargando pagos...</div>}{error && <div className="rounded-3xl border border-red-100 bg-red-50 p-5 font-bold text-red-700">{error}</div>}{!loading && !error && items.length === 0 && <div className="rounded-3xl border border-[#E9DED0] bg-white p-10 text-center"><div className="text-5xl">💳</div><h2 className="mt-4 text-xl font-black">No hay pagos pendientes</h2><p className="mt-2 text-sm font-semibold text-[#7A6F63]">Cuando una barbería envíe un pago aparecerá aquí.</p></div>}<div className="grid gap-4 xl:grid-cols-2">{items.map((item) => { const paymentId = Number(item.paymentId || 0); return <article key={paymentId || JSON.stringify(item)} className="rounded-3xl border border-[#E9DED0] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">{item.businessName || "-"}</h2><div className="mt-2 flex flex-wrap gap-2"><Chip>{item.plan || "-"}</Chip><Chip>{item.billingCycle || "-"}</Chip><Chip>{item.paymentMethod || "-"}</Chip></div></div><div className="rounded-2xl bg-emerald-50 px-4 py-3 text-right"><div className="text-xs font-black text-emerald-700">Monto</div><div className="text-xl font-black text-emerald-900">{item.amount ?? "-"} {item.currency || ""}</div></div></div><div className="mt-5 grid gap-2 text-sm font-bold text-[#7A6F63] sm:grid-cols-2"><Info label="Operación" value={item.operationNumber} /><Info label="Pagador" value={item.payerName} /><Info label="Teléfono" value={item.payerPhone} /><Info label="ID Pago" value={paymentId} /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button disabled={processingId === paymentId} onClick={() => approve(paymentId)} className="rounded-2xl bg-emerald-500 px-4 py-3 font-black text-white disabled:opacity-60">Aprobar</button><button disabled={processingId === paymentId} onClick={() => reject(paymentId)} className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 font-black text-red-700 disabled:opacity-60">Rechazar</button></div></article>; })}</div></div>;
}
function Chip({ children }) { return <span className="rounded-full bg-[#F4E8D7] px-3 py-1 text-xs font-black text-[#AF8750]">{children}</span>; }
function Info({ label, value }) { return <div><span className="text-[#AF8750]">{label}:</span> {value || "-"}</div>; }
