import { useEffect, useState } from 'react';
import { Check, Image, RefreshCw, X } from 'lucide-react';
import { getOwnerShowcase, moderateOwnerShowcase } from '../../api/ownerShowcaseApi';

const filters = [['PENDING_APPROVAL','Pendientes'],['PUBLISHED','Publicados'],['REJECTED','Rechazados'],['ARCHIVED','Archivados']];
export default function OwnerShowcasePage() {
  const [status,setStatus]=useState('PENDING_APPROVAL'); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [working,setWorking]=useState(0);
  async function load(){setLoading(true);setError('');try{setItems(await getOwnerShowcase(status));}catch(e){setError(e.message||'No se pudo cargar la vitrina.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[status]);
  async function moderate(item,next){let reason=null;if(next==='REJECTED'){reason=window.prompt('Motivo del rechazo para el profesional:','La imagen no cumple los criterios de publicacion.');if(reason===null)return;}setWorking(item.id);setError('');try{await moderateOwnerShowcase(item.id,next,reason);await load();}catch(e){setError(e.message||'No se pudo moderar.');}finally{setWorking(0);}}
  return <div className="space-y-6">
    <section className="overflow-hidden rounded-[32px] bg-[linear-gradient(135deg,#0F172A,#312E81)] p-7 text-white shadow-xl"><div className="flex items-center gap-3 text-amber-300"><Image size={24}/><span className="text-xs font-black uppercase tracking-[.22em]">Vitrina profesional</span></div><h1 className="mt-4 text-3xl font-black">Trabajos del equipo</h1><p className="mt-2 max-w-2xl text-sm font-semibold text-white/70">Revisa cada fotografia antes de mostrarla a los clientes. Solo el contenido aprobado aparece publicamente.</p></section>
    <section className="flex flex-wrap gap-2">{filters.map(([value,label])=><button key={value} onClick={()=>setStatus(value)} className={`rounded-full px-4 py-2 text-sm font-black ${status===value?'bg-neutral-950 text-white':'border border-neutral-200 bg-white text-neutral-600'}`}>{label}</button>)}<button onClick={load} className="ml-auto rounded-full border border-neutral-200 bg-white p-2.5"><RefreshCw size={18}/></button></section>
    {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700">{error}</div>}
    {loading?<div className="rounded-3xl bg-white p-10 text-center font-black">Cargando trabajos...</div>:items.length===0?<div className="rounded-3xl border border-dashed border-neutral-300 bg-white p-12 text-center"><Image className="mx-auto text-neutral-300" size={55}/><h2 className="mt-4 text-xl font-black">No hay trabajos en este estado</h2></div>:<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} className="overflow-hidden rounded-[26px] border border-neutral-200 bg-white shadow-sm"><div className="relative aspect-[4/3] bg-neutral-100">{item.mediaType === "VIDEO" ? <video src={item.imageUrl} poster={item.thumbnailUrl} controls preload="metadata" className="h-full w-full object-cover" /> : <img src={item.imageUrl} alt={item.title} className="h-full w-full object-cover"/>}<span className="absolute left-3 top-3 rounded-full bg-black/70 px-3 py-1 text-xs font-black text-white">{item.mediaType === "VIDEO" ? "VIDEO" : "FOTO"}</span></div><div className="p-5"><div className="text-xs font-black uppercase tracking-wider text-amber-700">{item.branchName}</div><h2 className="mt-2 text-xl font-black">{item.title}</h2><p className="mt-1 text-sm font-bold text-neutral-500">{item.professionalName}{item.serviceName?` · ${item.serviceName}`:''}</p>{item.description&&<p className="mt-3 text-sm text-neutral-600">{item.description}</p>}{item.rejectionReason&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{item.rejectionReason}</p>}{status==='PENDING_APPROVAL'&&<div className="mt-5 grid grid-cols-2 gap-3"><button disabled={working===item.id} onClick={()=>moderate(item,'REJECTED')} className="flex items-center justify-center gap-2 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 font-black text-red-700"><X size={18}/>Rechazar</button><button disabled={working===item.id} onClick={()=>moderate(item,'PUBLISHED')} className="flex items-center justify-center gap-2 rounded-2xl bg-emerald-500 px-4 py-3 font-black text-white"><Check size={18}/>Publicar</button></div>}</div></article>)}</div>}
  </div>;
}