function esc(value) { return String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); }
function sheet(name, rows) { const headers=rows.length?Object.keys(rows[0]):['Sin registros']; const row=(values,head=false)=>`<Row>${values.map(v=>`<Cell${head?' ss:StyleID="Header"':''}><Data ss:Type="${typeof v==='number'?'Number':'String'}">${esc(v)}</Data></Cell>`).join('')}</Row>`; return `<Worksheet ss:Name="${esc(name)}"><Table>${row(headers,true)}${rows.map(x=>row(headers.map(k=>x[k]??''))).join('')}</Table></Worksheet>`; }
function data(p) {
 const money=v=>Number(v||0);
 const summary=[{Periodo:`${p.from} a ${p.to}`,Sede:p.branchName,Ventas:money(p.salesReport?.totalSales),TicketPromedio:money(p.salesReport?.averageTicket),Gastos:money(p.expenseReport?.total),Utilidad:money(p.profitability?.netProfit),PagosProfesionales:money(p.professionalPaymentReport?.totalPaid)}];
 const comparison=Object.entries(p.periodComparison?.metrics||{}).map(([key,x])=>({Indicador:key,Actual:money(x.current),Anterior:money(x.previous),Diferencia:money(x.difference),VariacionPorcentaje:money(x.percentage)}));
 const barbers=(p.barbers||[]).map(x=>({Profesional:x.barberName,Ventas:money(x.totalSales),Servicios:Number(x.salesCount||0),TicketPromedio:money(x.averageTicket)}));
 const products=(p.productReport?.items||[]).map(x=>({Producto:x.productName,SKU:x.sku||'',Categoria:x.category,Unidades:Number(x.unitsSold||0),Ventas:Number(x.salesCount||0),Ingresos:money(x.revenue),CostoEstimado:money(x.estimatedCost),MargenEstimado:money(x.estimatedMargin)}));
 const expenses=(p.expenseReport?.items||[]).map(x=>({Fecha:String(x.date||'').slice(0,10),Tipo:x.type,Concepto:x.concept,Sede:x.branchName,Profesional:x.professional||'',Monto:money(x.amount)}));
 const payments=(p.professionalPaymentReport?.items||[]).map(x=>({Profesional:x.barberName,Sede:x.branchName,Desde:x.periodFrom,Hasta:x.periodTo,Estado:x.status,Sueldo:money(x.salaryAmount),Comision:money(x.commissionAmount),Propinas:money(x.tipsAmount),Adelantos:money(x.advancesApplied),Pagado:money(x.amountPaid),Pendiente:money(x.remainingAmount)}));
 return {summary,comparison,barbers,products,expenses,payments};
}
export function exportOwnerReportsExcel(payload){const d=data(payload);const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Header"><Font ss:Color="#FFFFFF" ss:Bold="1"/><Interior ss:Color="#111827" ss:Pattern="Solid"/></Style></Styles>${sheet('Resumen',d.summary)}${sheet('Comparativo',d.comparison)}${sheet('Profesionales',d.barbers)}${sheet('Productos',d.products)}${sheet('Gastos',d.expenses)}${sheet('Pagos',d.payments)}</Workbook>`;const url=URL.createObjectURL(new Blob([xml],{type:'application/vnd.ms-excel;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`reportes-${payload.from}-${payload.to}.xls`;a.click();URL.revokeObjectURL(url);}
export async function exportOwnerReportsPdf(payload){const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const d=data(payload);const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFillColor(15,23,42);doc.rect(0,0,297,28,'F');doc.setTextColor(245,196,81);doc.setFontSize(20);doc.text('Reporte ejecutivo GODS',12,13);doc.setTextColor(255,255,255);doc.setFontSize(9);doc.text(`${payload.branchName} | ${payload.from} a ${payload.to}`,12,21);let first=true;for(const [title,rows] of [['Resumen',d.summary],['Comparativo',d.comparison],['Profesionales',d.barbers],['Productos',d.products],['Gastos',d.expenses],['Pagos profesionales',d.payments]]){if(!first)doc.addPage();first=false;if(title!=='Resumen'){doc.setTextColor(17,24,39);doc.setFontSize(16);doc.text(title,12,15);}const headers=rows.length?Object.keys(rows[0]):['Sin registros'];autoTable(doc,{startY:title==='Resumen'?34:21,head:[headers],body:rows.map(r=>headers.map(k=>r[k]??'')),styles:{fontSize:7,cellPadding:2,textColor:[31,41,55]},headStyles:{fillColor:[15,23,42],textColor:[245,196,81]},alternateRowStyles:{fillColor:[248,250,252]},margin:{left:8,right:8}});}doc.save(`reportes-${payload.from}-${payload.to}.pdf`);}